In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [ ]:
data = pd.read_csv('wine_data.csv')

In [ ]:
df = data.copy()

In [ ]:
df.head()

fixed_acidity  volatile_acidity  citric_acid  residual_sugar  chlorides  \
0           11.6             0.580         0.66            2.20      0.074   
1           10.4             0.610         0.49            2.10      0.200   
2            7.4             1.185         0.00            4.25      0.097   
3           10.4             0.440         0.42            1.50      0.145   
4            8.3             1.020         0.02            3.40      0.084   

   free_sulfur_dioxide  total_sulfur_dioxide  density    pH  sulphates  \
0                 10.0                  47.0  1.00080  3.25       0.57   
1                  5.0                  16.0  0.99940  3.16       0.63   
2                  5.0                  14.0  0.99660  3.63       0.54   
3                 34.0                  48.0  0.99832  3.38       0.86   
4                  6.0                  11.0  0.99892  3.48       0.49   

   alcohol  quality  
0      9.0        3  
1      8.4        3  
2     10.7        3  
3      9.9        3  
4     11.0        3

In [ ]:
df.describe()

fixed_acidity  volatile_acidity   citric_acid  residual_sugar  \
count   21000.000000      21000.000000  21000.000000    21000.000000   
mean        9.797079          0.774796      0.793870       31.289348   
std         2.413919          0.365015      0.384833       19.015391   
min         3.800000          0.080000      0.000000        0.600000   
25%         7.600000          0.430000      0.410000        9.800000   
50%        10.000000          0.830000      0.870000       37.600000   
75%        11.800000          1.080000      1.110000       46.800000   
max        15.900000          1.580000      1.660000       65.800000   

          chlorides  free_sulfur_dioxide  total_sulfur_dioxide       density  \
count  21000.000000         21000.000000          21000.000000  21000.000000   
mean       0.200245           129.442333            229.008762      1.009972   
std        0.124933            77.167262            100.183265      0.012032   
min        0.009000             1.000000              6.000000      0.987110   
25%        0.072000            45.000000            150.000000      0.997417   
50%        0.205000           145.800000            240.500000      1.012200   
75%        0.298000           194.325000            311.625000      1.019840   
max        0.611000           289.000000            440.000000      1.038980   

                 pH     sulphates       alcohol       quality  
count  21000.000000  21000.000000  21000.000000  21000.000000  
mean       3.158712      1.020641     11.291716      6.000000  
std        0.171371      0.408304      1.182198      2.000048  
min        2.720000      0.220000      8.000000      3.000000  
25%        3.030000      0.620000     10.400000      4.000000  
50%        3.150000      1.080000     11.300000      6.000000  
75%        3.270000      1.360000     12.200000      8.000000  
max        4.010000      2.000000     14.900000      9.000000

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.decomposition import PCA

In [ ]:
df.columns

Index(['fixed_acidity', 'volatile_acidity', 'citric_acid', 'residual_sugar',
       'chlorides', 'free_sulfur_dioxide', 'total_sulfur_dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [ ]:
X = df.drop('quality', axis=1)
y = df['quality']

In [ ]:
# Select the features for scaling
features_to_scale = X.columns.to_list()

In [ ]:
scale = df[features_to_scale]
scaler = MinMaxScaler()

# Fit the scaler to the selected features
scaler.fit(scale)

MinMaxScaler()

In [ ]:
# Transform the selected features
X_scaled = scaler.transform(scale)


In [ ]:
print(X_scaled)

[[0.6446281  0.33333333 0.39759036 ... 0.41085271 0.19662921 0.14492754]
 [0.54545455 0.35333333 0.29518072 ... 0.34108527 0.23033708 0.05797101]
 [0.29752066 0.73666667 0.         ... 0.70542636 0.17977528 0.39130435]
 ...
 [0.79338843 0.25333333 0.62650602 ... 0.13178295 0.86516854 0.1884058 ]
 [0.23140496 0.63333333 0.65662651 ... 0.17054264 0.74157303 0.71014493]
 [0.45454545 0.56666667 0.79518072 ... 0.34108527 0.6741573  0.72463768]]


In [ ]:
# Specify the number of components to keep
pca = PCA(n_components=7)  # For example, keeping 2 principal components
pca.fit(X_scaled)
X_pca = pca.transform(X_scaled)
explained_variance = pca.explained_variance_ratio_
print(explained_variance)

[0.67100962 0.05386915 0.04403888 0.04043775 0.03647319 0.03131332
 0.03035266]


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X_pca, y, test_size=0.2, random_state=42)

In [ ]:
X_train.shape


(16800, 7)

In [ ]:
y_train.shape

(16800,)

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
model = Sequential()
model.add(Dense(128, activation='relu', input_shape=(X_train.shape[1],)))
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(7, activation='softmax'))

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.decomposition import PCA
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')


# Load the data
data = pd.read_csv('wine_data.csv')  # Replace 'wine_data.csv' with your data file
df = data.copy()

# Separate features and target
X = df.drop('quality', axis=1)
y = df['quality']

# Select the features for scaling
features_to_scale = X.columns.to_list()

# Scale the features
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X[features_to_scale])

# Perform PCA
pca = PCA(n_components=7)  # Adjust the number of components if needed
X_pca = pca.fit_transform(X_scaled)

# Split into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_pca, y, test_size=0.2, random_state=42)

# Convert target to categorical (only once)
y_train = tf.keras.utils.to_categorical(y_train - 3, num_classes=7)  # Assuming quality ratings from 3 to 9
y_test = tf.keras.utils.to_categorical(y_test - 3, num_classes=7)

# Create the model
model = Sequential()
model.add(Dense(128, activation='relu', input_shape=(X_train.shape[1],)))
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(7, activation='softmax'))

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=100, batch_size=10, validation_data=(X_test, y_test))

# Evaluate the model
_, accuracy = model.evaluate(X_test, y_test)
print('Accuracy: %.2f' % (accuracy*100))

Epoch 1/100
1680/1680 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - accuracy: 0.2827 - loss: 1.6438 - val_accuracy: 0.2864 - val_loss: 1.6039
Epoch 2/100
1680/1680 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.3032 - loss: 1.5767 - val_accuracy: 0.2919 - val_loss: 1.5921
Epoch 3/100
1680/1680 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.3079 - loss: 1.5664 - val_accuracy: 0.2940 - val_loss: 1.5869
Epoch 4/100
1680/1680 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.3119 - loss: 1.5645 - val_accuracy: 0.2871 - val_loss: 1.5946
Epoch 5/100
1680/1680 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.3075 - loss: 1.5636 - val_accuracy: 0.2881 - val_loss: 1.5828
Epoch 6/100
1680/1680 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.3178 - loss: 1.5553 - val_accuracy: 0.3019 - val_loss: 1.5780
Epoch 7/100
1680/1680 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.3163 - loss: 1.5494 - val_accuracy: 0.3052 - val_loss: 1.5728
Epoch 8/100
1680/1680 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.3236 - loss: 

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.model_selection import train_test_split, KFold
from sklearn.kernel_approximation import RBFSampler
from sklearn.preprocessing import MinMaxScaler
from sklearn.decomposition import PCA
import pandas as pd
import numpy as np

# Load the data
data = pd.read_csv('wine_data.csv')  # Replace 'wine_data.csv' with your data file
df = data.copy()

# Separate features and target
X = df.drop('quality', axis=1)
y = df['quality']

# Apply RBF filter
rbf_feature = RBFSampler(gamma=1, random_state=42)  # Adjust gamma as needed
X_rbf = rbf_feature.fit_transform(X)
X = np.concatenate([X, X_rbf], axis=1)  # Concatenate RBF feature

# Scale the data
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

# Perform PCA
pca = PCA(n_components=7)  # Adjust the number of components if needed
X_pca = pca.fit_transform(X_scaled)

# Split into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_pca, y, test_size=0.2, random_state=42)

# Convert target to categorical
y_train = tf.keras.utils.to_categorical(y_train - 3, num_classes=7)  # Assuming quality ratings from 3 to 9
y_test = tf.keras.utils.to_categorical(y_test - 3, num_classes=7)

# Define the model creation function
def create_model(neurons1=128, neurons2=64, neurons3=32, dropout_rate=0.2, learning_rate=0.001):
    model = Sequential()
    model.add(Dense(neurons1, activation='relu', input_shape=(X_train.shape[1],)))
    model.add(Dropout(dropout_rate))
    model.add(Dense(neurons2, activation='relu'))
    model.add(Dropout(dropout_rate))
    model.add(Dense(neurons3, activation='relu'))
    model.add(Dense(7, activation='softmax'))
    optimizer = tf.keras.optimizers.Adam(learning_rate=learning_rate)
    model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])
    return model

# Define hyperparameter grid
param_grid = {
    'neurons1': [32, 64, 128, 256],
    'neurons2': [16, 32, 64, 128],
    'neurons3': [8, 16, 32, 64],
    'dropout_rate': [0.1, 0.2, 0.3, 0.4, 0.5],
    'batch_size': [16, 32, 64, 128],
    'epochs': [50, 100, 150, 200],
    'learning_rate': [1e-4, 1e-3, 1e-2]  # Adjust learning rates as needed
}

# Manual hyperparameter tuning loop
best_accuracy = 0
best_params = {}

for neurons1 in param_grid['neurons1']:
    for neurons2 in param_grid['neurons2']:
        for neurons3 in param_grid['neurons3']:
            for dropout_rate in param_grid['dropout_rate']:
                for batch_size in param_grid['batch_size']:
                    for epochs in param_grid['epochs']:
                        for learning_rate in param_grid['learning_rate']:
                            # Create and train the model
                            model = create_model(neurons1, neurons2, neurons3, dropout_rate, learning_rate)
                            early_stopping = EarlyStopping(monitor='val_loss', patience=10)
                            history = model.fit(X_train, y_train, epochs=epochs, batch_size=batch_size,
                                                validation_split=0.2, callbacks=[early_stopping], verbose=0)

                            # Evaluate the model
                            _, accuracy = model.evaluate(X_test, y_test, verbose=0)

                            # Update best parameters if accuracy is improved
                            if accuracy > best_accuracy:
                                best_accuracy = accuracy
                                best_params = {'neurons1': neurons1, 'neurons2': neurons2, 'neurons3': neurons3,
                                               'dropout_rate': dropout_rate, 'batch_size': batch_size,
                                               'epochs': epochs, 'learning_rate': learning_rate}

# Print best hyperparameters and accuracy
print("Best accuracy:", best_accuracy)
print("Best parameters:", best_params)

# Train the best model
best_model = create_model(**best_params)
early_stopping = EarlyStopping(monitor='val_loss', patience=10)
history = best_model.fit(X_train, y_train, epochs=best_params['epochs'],
                        batch_size=best_params['batch_size'], validation_split=0.2,
                        callbacks=[early_stopping], verbose=0)

# Evaluate the final model
_, final_accuracy = best_model.evaluate(X_test, y_test, verbose=0)
print('Final accuracy: %.2f' % (final_accuracy * 100))